services:
  db:
    image: postgres:17
    container_name: drf_celery_tutorial_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - drf_celery_tutorial_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    # image: rabbitmq:4-management
    image: rabbitmq:4.2-management
    container_name: drf_celery_tutorial_rabbitmq
    ports:
      - "${CELERY_BROKER_PORT}:5672"
      - "${CELERY_BROKER_MANAGEMENT_PORT}:15672"
    volumes:
      - drf_celery_tutorial_rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  drf_celery_tutorial_postgres_data:
  drf_celery_tutorial_rabbitmq_data:
